# release_build.ps1 — Build a release APK with full pre-flight checks.
# This is the ONLY supported way to produce a release APK locally.
# Run from the repo root:  ./scripts/release_build.ps1
#
# Requirements:
#   - A release.keystore file at the repo root.
#   - env/firebase_config.json must exist (generated by CI or copied from example).
#   - The script will prompt for keystore password if KEYSTORE_PASSWORD is not set.

$ErrorActionPreference = "Stop"
$rootDir = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $rootDir

Write-Host "=== 1/5: Clean ==="
flutter clean
if (-not $?) { exit 1 }

Write-Host "=== 2/5: Get dependencies ==="
flutter pub get
if (-not $?) { exit 1 }

Write-Host "=== 3/5: Analyze ==="
flutter analyze
if (-not $?) { exit 1 }

Write-Host "=== 4/5: Test ==="
flutter test
if (-not $?) { exit 1 }

# Keystore setup — prompt if not already set
if (-not $env:KEYSTORE_PATH) {
    $ks = Get-Item "$rootDir\release.keystore" -ErrorAction SilentlyContinue
    if ($ks) {
        $env:KEYSTORE_PATH = $ks.FullName
        Write-Host "  Using keystore: $($env:KEYSTORE_PATH)"
    } else {
        Write-Error "No release.keystore found at repo root. Generate one first:"
        Write-Error "  keytool -genkey -v -keystore release.keystore -alias upload -keyalg RSA -keysize 2048 -validity 10000"
        exit 1
    }
}
if (-not $env:KEYSTORE_PASSWORD) {
    $secure = Read-Host "Enter keystore password" -AsSecureString
    $ptr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    $env:KEYSTORE_PASSWORD = [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
}
if (-not $env:KEY_ALIAS) { $env:KEY_ALIAS = "upload" }
if (-not $env:KEY_PASSWORD) { $env:KEY_PASSWORD = $env:KEYSTORE_PASSWORD }

Write-Host "=== 5/5: Build release APK ==="
flutter build apk --release --dart-define-from-file=env/firebase_config.json
if (-not $?) { exit 1 }

Write-Host ""
Write-Host "✓ Release APK built: build/app/outputs/flutter-apk/app-release.apk"
