#!/usr/bin/env bash
set -euo pipefail

# release_build.sh — Build a release APK with full pre-flight checks.
# This is the ONLY supported way to produce a release APK locally.
# Run from the repo root:  ./scripts/release_build.sh
#
# Requirements:
#   - KEYSTORE_PATH, KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD must be set
#     (or a release.keystore at the repo root with matching env vars).
#   - env/firebase_config.json must exist (generated by CI or copied from example).

cd "$(git rev-parse --show-toplevel)"

echo "=== 1/5: Clean ==="
flutter clean

echo "=== 2/5: Get dependencies ==="
flutter pub get

echo "=== 3/5: Analyze ==="
flutter analyze

echo "=== 4/5: Test ==="
flutter test

echo "=== 5/5: Build release APK ==="
flutter build apk --release --dart-define-from-file=env/firebase_config.json

echo ""
echo "✓ Release APK built: build/app/outputs/flutter-apk/app-release.apk"
